### ISSUE TITLE
generator failed: topk() got an unexpected keyword argument 'out'

### ISSUE THREAD

**Issue by wangyirui** [facebookresearch/fairseq-py#109]
I am running generate.py to check the translation performance. But I got an error :
###############################################################################
Traceback (most recent call last):
  File "generate.py", line 140, in <module>
    main()
  File "generate.py", line 92, in main
    for sample_id, src_tokens, target_tokens, hypos in translations:
  File "/home/kimi/Desktop/fairseq-py/fairseq/sequence_generator.py", line 77, in generate_batched_itr
    maxlen=int(maxlen_a*srclen + maxlen_b))
  File "/home/kimi/Desktop/fairseq-py/fairseq/sequence_generator.py", line 92, in generate
    return self._generate(src_tokens, beam_size, maxlen)
  File "/home/kimi/Desktop/fairseq-py/fairseq/sequence_generator.py", line 248, in _generate
    out=(cand_scores, cand_indices))
TypeError: topk() got an unexpected keyword argument 'out'
################################################################################

I set a breakpoint to check this error and find that both cand_scores and cand_indices are empty. I guess it may result in this error.

**Comment by myleott** [comment]
What version of PyTorch are you using? The latest update requires >= 0.4.0, i.e., building from source (we will update the README to reflect this).

**Comment by wangyirui** [comment]
I am using 0.4.0a0+a011853. And this fairseq-py is not the latest version, I cloned it about 2 or 3 days ago
