### ISSUE TITLE
Error with generate.py and interactive.py

### ISSUE THREAD

**Issue by enferas** [facebookresearch/fairseq-py#112]
I am using Amazon aws for making the training and testing for the model.
After it finished the training, it is giving this error when I try to use the generate.py or interactive.py

`Traceback (most recent call last):  
                                                                                                                 
File "generate.py", line 152, in module   
                                                                                                        main(args)   
                                                                                                                                    File "generate.py", line 95, in main      
                                                                                                           for sample_id, src_tokens, target_tokens, hypos in translations:     
                                                                            File "/home/ubuntu/fairseq/fairseq-py/fairseq/sequence_generator.py", line 77, in generate_batched_itr      
                                         prefix_tokens=s['target'][:, :prefix_size] if prefix_size > 0 else None,         
                                                                File "/home/ubuntu/fairseq/fairseq-py/fairseq/sequence_generator.py", line 90, in generate          
                                                 return self._generate(src_tokens, src_lengths, beam_size, maxlen, prefix_tokens)               
                                                  File "/home/ubuntu/fairseq/fairseq-py/fairseq/sequence_generator.py", line 355, in _generate             
                                            out=scores[:, step].view(bsz, beam_size),      
                                                                                                RuntimeError: invalid argument 2: input is not contiguous at /opt/conda/conda-bld/pytorch_1512387374934/work/torch/lib/THC/generic/THCTensor.c:227 `

**Comment by myleott** [comment]
Can you share more details about:
- PyTorch version
- fairseq-py version
- which model type and dataset you're using

**Comment by enferas** [comment]
It was PyTorch 0.3.0.post4.
So I made anaconda environment and install PyTorch 0.4.0 from the source using Docker image.
https://github.com/pytorch/pytorch#docker-image
Because it is not supporting yet from Amazon.

Then I had the same this issue https://github.com/facebookresearch/fairseq-py/issues/109.
So I made pull again and the problem solved.
