### ISSUE TITLE
Using more than 1 GPU

### ISSUE THREAD

**Issue by mali-nuist** [facebookresearch/fairseq-py#128]
**Errors appears when i train the model use the multi-gpu, the command is ：**
    
        CUDA_VISIBLE_DEVICES=0,1 python3  /DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/train.py  ./prprocessed   --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000  --arch fconv --save-dir ./checkpoints --skip-invalid-size-inputs-valid-test

**And the error is list below:**
     | distributed init (rank 1): tcp://localhost:15652
Traceback (most recent call last):
  File "/DATA/sdb/pytorch/mali_torch/lib/python3.5/os.py", line 42, in _get_exports_list
    return list(module.__all__)
AttributeError: module '_socket' has no attribute '__all__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/train.py", line 9, in <module>
    from fairseq import options
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/fairseq/options.py", line 10, in <module>
    import torch
  File "/usr/local/lib/python3.5/dist-packages/torch/__init__.py", line 310, in <module>
    import torch.multiprocessing
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/__init__.py", line 17, in <module>
    from .reductions import init_reductions
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 5, in <module>
    from multiprocessing.reduction import ForkingPickler
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 15, in <module>
    import socket
  File "/usr/lib/python3.5/socket.py", line 65, in <module>
    __all__.extend(os._get_exports_list(_socket))
  File "/DATA/sdb/pytorch/mali_torch/lib/python3.5/os.py", line 44, in _get_exports_list
    return [n for n in dir(module) if n[0] != '_']
KeyboardInterrupt
Traceback (most recent call last):
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/train.py", line 29, in <module>
    main(args)
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/train.py", line 21, in main
    multiprocessing_main(args)
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/multiprocessing_train.py", line 40, in main
    p.join()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/multiprocessing_train.py", line 82, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably be ignored --

Traceback (most recent call last):
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/multiprocessing_train.py", line 45, in run
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/DATA/sdb/pytorch/fairseq-py-dist/fairseq-py/fairseq/distributed_utils.py", line 23, in distributed_init
    world_size=args.distributed_world_size, rank=args.distributed_rank)
  File "/usr/local/lib/python3.5/dist-packages/torch/distributed/__init__.py", line 49, in init_process_group
    group_name, rank)
RuntimeError: _Map_base::at

**Besides, the newest code requires the 0.4.0 version pytorch according to the README(Currently fairseq-py requires PyTorch version >= 0.4.0. Please follow the instructions here: ) , but the latest pytorch seems to be 0.3.0 ...**

Thanks...

**Comment by myleott** [comment]
The latest version of fairseq-py requires building PyTorch from source: https://github.com/pytorch/pytorch#from-source.

Alternatively you can use an older version of fairseq-py that is compatible with PyTorch 0.3.0: https://github.com/facebookresearch/fairseq-py/tree/v0.3.0

**Comment by mali-nuist** [comment]
thanks
