### ISSUE TITLE
"index out of range" when preparing WMT14en2de

### ISSUE THREAD

**Issue by hitvoice** [facebookresearch/fairseq-py#132]
When running 
```sh
cd data
bash prepare-wmt14en2de.sh
```
An "IndexError" is reported:
```
Tokenizer Version 1.1
Language: de
Number of threads: 8

splitting train and valid...
learn_bpe.py on wmt14_en_de/tmp/train.de-en...
Traceback (most recent call last):
  File "subword-nmt/learn_bpe.py", line 254, in <module>
    main(args.input, args.output, args.symbols, args.min_frequency, args.verbose, is_dict=args.dict_input)
  File "subword-nmt/learn_bpe.py", line 199, in main
    vocab = dict([(tuple(x[:-1])+(x[-1]+'</w>',) ,y) for (x,y) in vocab.items()])
  File "subword-nmt/learn_bpe.py", line 199, in <listcomp>
    vocab = dict([(tuple(x[:-1])+(x[-1]+'</w>',) ,y) for (x,y) in vocab.items()])
IndexError: string index out of range
apply_bpe.py to train.en...
apply_bpe.py to valid.en...
apply_bpe.py to test.en...
apply_bpe.py to train.de...
apply_bpe.py to valid.de...
apply_bpe.py to test.de...
clean-corpus.perl: processing wmt14_en_de/tmp/bpe.train.en & .de to wmt14_en_de/train, cutoff 1-250, ratio 1.5
..........(100000)..........(200000)..........(300000)..........(400000)..........(500000)..........(600000)..........(700000)..........(800000)..........(900000)..........(1000000)..........(1100000)..........(1200000)..........(1300000)..........(1400000)..........(1500000)..........(1600000)..........(1700000)..........(1800000)..........(1900000)..........(2000000)..........(2100000)..........(2200000)..........(2300000)..........(2400000)..........(2500000)..........(2600000)..........(2700000)..........(2800000)..........(2900000)..........(3000000)..........(3100000)..........(3200000)..........(3300000)..........(3400000)..........(3500000)..........(3600000)..........(3700000)..........(3800000)..........(3900000)..........(4000000)..........(4100000)..........(4200000)..........(4300000)..........(4400000)..........(4500000)....
Input sentences: 4544200  Output sentences:  3557596
clean-corpus.perl: processing wmt14_en_de/tmp/bpe.valid.en & .de to wmt14_en_de/valid, cutoff 1-250, ratio 1.5
....
Input sentences: 45901  Output sentences:  36073
```
And the file `wmt14_en_de/code` only contains:
```
#version: 0.2
```
which is not expected. Further debugging shows that there are empty lines and multiple spaces in `wmt14_en_de/tmp/train.de-en`, and "subword-nmt/learn_bpe.py" is not robust enough. Starting from line 68 of "learn_bpe.py":
```python
for word in line.strip().split(' '):
    vocab[word] += 1
```
This will treat the empty string as a word when the line is empty or there're multiple blank characters in a sentence. My temporary workaround is to modify "learn_bpe.py":
```python
for word in line.strip().split(' '):
    if word:
        vocab[word] += 1
```
And everything looks fine. The output following "python learn_bpe.py ..." becomes:
```
apply_bpe.py to train.en...
apply_bpe.py to valid.en...
apply_bpe.py to test.en...
apply_bpe.py to train.de...
apply_bpe.py to valid.de...
apply_bpe.py to test.de...
clean-corpus.perl: processing wmt14_en_de/tmp/bpe.train.en & .de to wmt14_en_de/train, cutoff 1-250, ratio 1.5
..........(100000)..........(200000)..........(300000)..........(400000)..........(500000)..........(600000)..........(700000)..........(800000)..........(900000)..........(1000000)..........(1100000)..........(1200000)..........(1300000)..........(1400000)..........(1500000)..........(1600000)..........(1700000)..........(1800000)..........(1900000)..........(2000000)..........(2100000)..........(2200000)..........(2300000)..........(2400000)..........(2500000)..........(2600000)..........(2700000)..........(2800000)..........(2900000)..........(3000000)..........(3100000)..........(3200000)..........(3300000)..........(3400000)..........(3500000)..........(3600000)..........(3700000)..........(3800000)..........(3900000)..........(4000000)..........(4100000)..........(4200000)..........(4300000)..........(4400000)..........(4500000)....
Input sentences: 4544200  Output sentences:  3960793
clean-corpus.perl: processing wmt14_en_de/tmp/bpe.valid.en & .de to wmt14_en_de/valid, cutoff 1-250, ratio 1.5
....
Input sentences: 45901  Output sentences:  40062
```
and `wmt14_en_de/code` now has 40001 lines in total (1 version + 40000 symbols). The first 10 lines of `wmt14_en_de/code`:
```
#version: 0.2
e n</w>
e r
i n
t h
c h
e n
e r</w>
a n
u n
```

Since [subword-nmt](https://github.com/rsennrich/subword-nmt) is another project,  is there a more elegant way to do this? I've tried the following script to remove empty lines:
```sh
mv wmt14_en_de/tmp/train.de-en wmt14_en_de/tmp/train.de-en.orig
sed "/^[[:space:]]*$/d" wmt14_en_de/tmp/train.de-en.orig > wmt14_en_de/tmp/train.de-en
```
but there are multiple spaces in the original text and the "IndexError" still appears.

@edunov Is this observed in the original testing of PR #91 as well? Am I getting something wrong along the way?

My environment:
- OS: Ubuntu 16.04.3 LTS
- Python version: 3.6.2

"fairseq-py" is cloned after commit 49aeab2d59b96933424e06685392eaed6a06e324 and "subword-nmt" is cloned after commit 1d4c3ca4e92e7387fb640ee619c8208b2e24b84c.

**Comment by edunov** [comment]
Hi @hitvoice 
I haven't seen this error before. Trying to reproduce now, will post an update when my run is complete. 

There were a lot of changes in subword-nmt recently, can you try an older version, e.g. this one: 8247488c351be0a7a32b6ab9fa2db05a8744882c  ?

**Comment by hitvoice** [comment]
I switched subword-nmt to 8247488c351be0a7a32b6ab9fa2db05a8744882c and ran the script again. Now everything looks like the modified version:
```
apply_bpe.py to train.en...
apply_bpe.py to valid.en...
apply_bpe.py to test.en...
apply_bpe.py to train.de...
apply_bpe.py to valid.de...
apply_bpe.py to test.de...
clean-corpus.perl: processing wmt14_en_de/tmp/bpe.train.en & .de to wmt14_en_de/train, cutoff 1-250, ratio 1.5
..........(100000)..........(200000)..........(300000)..........(400000)..........(500000)..........(600000)..........(700000)..........(800000)..........(900000)..........(1000000)..........(1100000)..........(1200000)..........(1300000)..........(1400000)..........(1500000)..........(1600000)..........(1700000)..........(1800000)..........(1900000)..........(2000000)..........(2100000)..........(2200000)..........(2300000)..........(2400000)..........(2500000)..........(2600000)..........(2700000)..........(2800000)..........(2900000)..........(3000000)..........(3100000)..........(3200000)..........(3300000)..........(3400000)..........(3500000)..........(3600000)..........(3700000)..........(3800000)..........(3900000)..........(4000000)..........(4100000)..........(4200000)..........(4300000)..........(4400000)..........(4500000)....
Input sentences: 4544200  Output sentences:  3960793
clean-corpus.perl: processing wmt14_en_de/tmp/bpe.valid.en & .de to wmt14_en_de/valid, cutoff 1-250, ratio 1.5
....
Input sentences: 45901  Output sentences:  40062
```
`wmt14_en_de/code` has 40001 lines and also looks fine.

I proceeded and found another problem. In data/README the command to train the wmt14en2de dataset is:
```sh
python train.py data-bin/wmt14_en_de \
  --lr 0.5 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 \
  --label-smoothing 0.1 --force-anneal 50 \
  --arch fconv_wmt_en_de --save-dir checkpoints/fconv_wmt_en_de
```
but there's no argument named "label-smoothing" or "force-anneal". It seems that the README file is tested on an older version of this project. Is it fine to omit these two?

**Comment by myleott** [comment]
Right, we need to update the README. Please add the `--criterion label_smoothed_cross_entropy` and `--lr-scheduler fixed` arguments:
```
python train.py data-bin/wmt14_en_de \
  --lr 0.5 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 \
  --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
  --lr-scheduler fixed --force-anneal 50 \
  --arch fconv_wmt_en_de --save-dir checkpoints/fconv_wmt_en_de
```

**Comment by edunov** [comment]
The issue in subword-nmt should be fixed now: 
https://github.com/rsennrich/subword-nmt/issues/41
