### ISSUE TITLE
"Variable" object has no attribute "conv_tbc"

### ISSUE THREAD

**Issue by SilencerChen** [facebookresearch/fairseq-py#133]
I followed the readme to start train the model.But the problem is always here.
Does anyone else have the same question? How do you fix it.

CUDA_VISIBLE_DEVICES=3 python train.py data-bin/iwslt14.tokenized.de-en   --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000   --arch fconv_iwslt_de_en --save-dir checkpoints/fconv
Namespace(arch='fconv_iwslt_de_en', clip_norm=0.1, criterion='cross_entropy', curriculum=0, data='data-bin/iwslt14.tokenized.de-en', decoder_attention='True', decoder_embed_dim=256, decoder_layers='[(256, 3)] * 3', decoder_out_embed_dim=256, device_id=0, distributed_backend='nccl', distributed_init_method=None, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.2, encoder_embed_dim=256, encoder_layers='[(256, 3)] * 4', log_format=None, log_interval=1000, lr=[0.25], lr_scheduler='reduce_lr_on_plateau', lr_shrink=0.1, max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=4000, min_lr=1e-05, momentum=0.99, no_epoch_checkpoints=False, no_progress_bar=False, no_save=False, optimizer='nag', restore_file='checkpoint_last.pt', sample_without_replacement=0, save_dir='checkpoints/fconv', save_interval=-1, seed=1, sentence_avg=False, share_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, train_subset='train', valid_subset='valid', weight_decay=0.0)
| [de] dictionary: 8853 types
| [en] dictionary: 6629 types
| data-bin/iwslt14.tokenized.de-en train 160215 examples
| data-bin/iwslt14.tokenized.de-en valid 7282 examples
| model fconv_iwslt_de_en, criterion CrossEntropyCriterion
| num. model params: 9618122
| training on 1 GPUs
| max tokens per GPU = 4000 and max sentences per GPU = None
| epoch 001:   0%|                                                                                                                                         | 0/1090 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 29, in <module>
    main(args)
  File "train.py", line 23, in main
    singleprocess_main(args)
  File "/home/kuncheng/Code/video_caption/fairseq/singleprocess_train.py", line 79, in main
    train(args, trainer, dataset, epoch, batch_offset)
  File "/home/kuncheng/Code/video_caption/fairseq/singleprocess_train.py", line 138, in train
    log_output = trainer.train_step(sample)
  File "/home/kuncheng/Code/video_caption/fairseq/fairseq/trainer.py", line 94, in train_step
    loss, sample_sizes, logging_outputs, ooms_fwd = self._forward(sample)
  File "/home/kuncheng/Code/video_caption/fairseq/fairseq/trainer.py", line 142, in _forward
    loss, sample_size, logging_output_ = self.criterion(self.model, sample)
  File "/home/kuncheng/anaconda3/envs/torch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kuncheng/Code/video_caption/fairseq/fairseq/criterions/cross_entropy.py", line 28, in forward
    net_output = model(**sample['net_input'])
  File "/home/kuncheng/anaconda3/envs/torch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kuncheng/Code/video_caption/fairseq/fairseq/models/fairseq_model.py", line 43, in forward
    encoder_out = self.encoder(src_tokens, src_lengths)
  File "/home/kuncheng/anaconda3/envs/torch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kuncheng/Code/video_caption/fairseq/fairseq/models/fconv.py", line 122, in forward
    x = conv(x)
  File "/home/kuncheng/anaconda3/envs/torch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kuncheng/Code/video_caption/fairseq/fairseq/modules/conv_tbc.py", line 32, in forward
    return input.contiguous().conv_tbc(self.weight, self.bias, self.padding[0])
  File "/home/kuncheng/anaconda3/envs/torch36/lib/python3.6/site-packages/torch/autograd/variable.py", line 67, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Variable' object has no attribute 'conv_tbc'

**Comment by myleott** [comment]
fairseq-py requires a recent version of PyTorch, built from source. See #127.
