### ISSUE TITLE
fairseq setup build, gcc failed with exit status 1

### ISSUE THREAD

**Issue by youshimanon** [facebookresearch/fairseq-py#19]
When I run 'python setup.py build' in fairseq-py, it turned out 'command 'gcc' failed with exit status 1, what does this mean?

**Comment by edunov** [comment]
That means gcc failed to compile the source code. If you need help to diagnose this error, please paste the entire output here.

**Comment by youshimanon** [comment]
Hi, below is the entire output.

running build
running build_py
generating /tmp/tmpm_34tltw/_temporal_convolution_tbc.c
running build_ext
building '_temporal_convolution_tbc' extension
creating scratch
creating scratch/jiajie.ding
creating scratch/jiajie.ding/fairseq-py
creating scratch/jiajie.ding/fairseq-py/fairseq
creating scratch/jiajie.ding/fairseq-py/fairseq/clib
creating scratch/jiajie.ding/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall
-Wstrict-prototypes -fPIC -DWITH_CUDA
-I/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include
-I/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH
-I/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC
-I/scratch/jiajie.ding/miniconda3/include/python3.6m -c
_temporal_convolution_tbc.c -o ./_temporal_convolution_tbc.o
-std=c++11
cc1: warning: command line option '-std=c++11' is valid for C++/ObjC++
but not for C [enabled by default]
In file included from
/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THC.h:4:0,
                 from _temporal_convolution_tbc.c:434:
/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:9:18:
fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
Traceback (most recent call last):
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/unixccompiler.py",
line 118, in _compile
    extra_postargs)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/ccompiler.py",
line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/spawn.py",
line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/spawn.py",
line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/cffi/ffiplatform.py",
line 49, in _build
    dist.run_command('build_ext')
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/dist.py",
line 974, in run_command
    cmd_obj.run()
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/build_ext.py",
line 77, in run
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/command/build_ext.py",
line 339, in run
    self.build_extensions()
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/command/build_ext.py",
line 448, in build_extensions
    self._build_extensions_serial()
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/command/build_ext.py",
line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/build_ext.py",
line 198, in build_extension
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/command/build_ext.py",
line 533, in build_extension
    depends=ext.depends)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/ccompiler.py",
line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/unixccompiler.py",
line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    'build_py': build_py_hook,
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/core.py",
line 148, in setup
    dist.run_commands()
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/dist.py",
line 955, in run_commands
    self.run_command(cmd)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/dist.py",
line 974, in run_command
    cmd_obj.run()
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/command/build.py",
line 135, in run
    self.run_command(cmd_name)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/cmd.py",
line 313, in run_command
    self.distribution.run_command(command)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/distutils/dist.py",
line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    conv_tbc.build()
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py",
line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py",
line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/cffi/api.py",
line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/cffi/recompiler.py",
line 1484, in recompile
    compiler_verbose, debug)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/cffi/ffiplatform.py",
line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/scratch/jiajie.ding/miniconda3/lib/python3.6/site-packages/cffi/ffiplatform.py",
line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with
exit status 1

**Comment by edunov** [comment]
It fails to find CUDA in your system. Do you have cuda installed? You can check by running nvcc --version  It should print something like this:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

If you do, try adding CUDA headers to build path: 
```
export CPATH={PATH TO YOUR CUDA INSTALLATION}/cuda-8.0/include 
```

**Comment by youshimanon** [comment]
Yes, I have conda installed, and below is the out put of export CPATH={PATH TO YOUR CUDA INSTALLATION}/cuda-8.0/include

[jiajie.ding@penzias fairseq-py]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44
[jiajie.ding@penzias fairseq-py]$ export CPATH={PATH TO YOUR CUDA
INSTALLATION}/cuda-8.0/include
-bash: export: `INSTALLATION}/cuda-8.0/include': not a valid identifier

**Comment by youshimanon** [comment]
Sorry, I got it

**Comment by youshimanon** [comment]
I tried to locate cuda-8.0 but could not find the path. How do I find the path it installed?

**Comment by youshimanon** [comment]
I have cuda installed 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

But how do I find the path where it was installed. I couldn't  locate it.

**Comment by edunov** [comment]
It is usually somewhere in /usr/local/cuda,  but it depends on the system. 
Try to check 
```
which nvcc
```
maybe it will give you a hint.
Otherwise, there is always a brute force approach:
```
find / -name cuda.h
```
That will scan your entire file system for anything called cuda.h

**Comment by youshimanon** [comment]
It has been built. Thanks.

**Comment by trdat** [comment]
it worked for me!
`sudo apt install gcc python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev g++`
