### ISSUE TITLE
OS X - Error compiling temporal_convolution_tbc

### ISSUE THREAD

**Issue by stovenator** [facebookresearch/fairseq-py#20]
OS: OS X 10.13 High Sierra
CUDA: v. 9.0

When trying to compile fairseq-py on OSX, I'm getting the error:
> error: non-const lvalue reference to type 'at::Tensor' cannot bind to a temporary of type 'int'

I've tried using g++ , with similar results:
>error: invalid initialization of non-const reference of type 'at::Tensor&' from an rvalue of type 'int'

Here's the full output:

`
$ CC=clang++ python setup.py build
running build
running build_py
generating /var/folders/1f/z12pg_yx2194lgdvlb_kprb40000gp/T/tmpemf541ha/_temporal_convolution_tbc.c
running build_ext
building '_temporal_convolution_tbc' extension
creating Users
creating Users/mastover
creating Users/mastover/git
creating Users/mastover/git/fairseq-py
creating Users/mastover/git/fairseq-py/fairseq
creating Users/mastover/git/fairseq-py/fairseq/clib
creating Users/mastover/git/fairseq-py/fairseq/clib/temporal_convolution_tbc
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -DWITH_CUDA -I/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/Developer/NVIDIA/CUDA-9.0/include -I/Developer/NVIDIA/CUDA-8.0/include -I/Users/mastover/anaconda3/include/python3.6m -c _temporal_convolution_tbc.c -o ./_temporal_convolution_tbc.o -std=c++11
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -DWITH_CUDA -I/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/Developer/NVIDIA/CUDA-9.0/include -I/Developer/NVIDIA/CUDA-8.0/include -I/Users/mastover/anaconda3/include/python3.6m -c /Users/mastover/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./Users/mastover/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
/Users/mastover/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:70:21: error: non-const lvalue reference to type 'at::Tensor' cannot bind to a temporary of type 'int'
      at::addmm_out(1, O, 1, I, W, O);
                    ^
/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1203:43: note: passing argument to parameter 'result' here
static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                                          ^
/Users/mastover/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:111:21: error: non-const lvalue reference to type 'at::Tensor' cannot bind to a temporary of type 'int'
      at::addmm_out(1, dI, 1, dO, weight[k].t(), dI);
                    ^
/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1203:43: note: passing argument to parameter 'result' here
static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                                          ^
/Users/mastover/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:124:21: error: non-const lvalue reference to type 'at::Tensor' cannot bind to a temporary of type 'int'
      at::addmm_out(1, dW, 1, I, dO, dW);
                    ^
/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1203:43: note: passing argument to parameter 'result' here
static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta, Scalar alpha) {
                                          ^
/Users/mastover/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:129:20: error: reference to type 'const at::Tensor' could not bind to an rvalue of type 'int'
  at::sum_out(tmp, 0, dBias);
                   ^
/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/ATen/Functions.h:1044:64: note: passing argument to parameter 'self' here
static inline Tensor & sum_out(Tensor & result, const Tensor & self, int64_t dim, bool keepdim) {
                                                               ^
4 errors generated.
Traceback (most recent call last):
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'clang++' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'clang++' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    'build_py': build_py_hook,
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/mastover/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    conv_tbc.build()
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Users/mastover/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'clang++' failed with exit status 1
`

**Comment by edunov** [comment]
I have never tried to compile it on OS X, so there is not much I can tell. But you can try no_conv_tbc branch:
https://github.com/facebookresearch/fairseq-py/tree/no_conv_tbc 
This is the same model, but without ConvTBC, it is a bit slower, and you will not be able to use pre-trained models, but maybe you can make it work on your system.

**Comment by stovenator** [comment]
So, looking at this, it appears that the definition in my local copy of ATen/Functions.h, the only definition for addmm_out is:

`static inline Tensor & addmm_out(Tensor & result, const Tensor & self, const Tensor & mat1, const Tensor & mat2, Scalar beta=1, Scalar alpha=1);`

I'm guessing that in the version of pytorch I built, that this has changed. It appears that in temporal_convolution_tbc.cpp , we are trying to pass in integers, not tensors, for the first three arguments:

`at::addmm_out(1, 0, 1, I, W, O);`

**Comment by colesbury** [comment]
Oops. I changed the argument ordering in ATen. We need to update the call in fairseq-py.
