### ISSUE TITLE
"python setup.py build" not fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by teju85** [facebookresearch/fairseq-py#3]
Hi,
I'm following the setup instructions as in the README.md here: https://github.com/facebookresearch/fairseq-py#requirements-and-installation
Was able to get pytorch installed from source at commit-id: a03e5cb4, as per this readme. After this, I clone the fairseq-py repo. Also was able to install requirements for this repo. But, when I try to build and install fairseq-py, I see the following error:
```bash
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    readme = f.read()
  File "/opt/conda/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4007: ordinal not in range(128)
```

The issue is with line 89 in the README.md having unicode chars. This seems to be causing the error in installation. Simplest hack that took me past this error was to replace this line.
```bash
$ grep -v Pourquoi README.md > README.md.bak
$ mv README.md.bak README.md
```
After this, I was able to install fairseq-py successfully.

FWIW, my full system info is given at the end.

Regards,
Thejaswi

My system info:
```bash
$ uname -a
Linux 92bc62ee5c27 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

$ python --version
Python 3.5.2 :: Continuum Analytics, Inc.

$ conda --version
conda 4.3.25

$ gcc --version
gcc (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

$ ls /usr/local/cuda/lib64/libcudnn*
/usr/local/cuda/lib64/libcudnn.so  /usr/local/cuda/lib64/libcudnn.so.6  /usr/local/cuda/lib64/libcudnn.so.6.0.21  /usr/local/cuda/lib64/libcudnn_static.a
```

**Comment by teju85** [comment]
My bad. I forgot to mention that I was working over-and-above the dockerfile provided by pytorch repo.
Natalia Gimelshein pointed me to a fix for this case: https://github.com/docker-library/python/issues/13. With this I no more need the above hack.
```bash
$ export LANG=C.UTF-8
$ python setup.py build
$ python setup.py develop
```
Closing.
