### ISSUE TITLE
Unable to restore pre-trained models during training

### ISSUE THREAD

**Issue by aviralkumar2907** [facebookresearch/fairseq-py#52]
I ran this command: 

`python train.py data-bin/wmt14.en-fr.newstest2014/ --restore-file wmt14.en-fr.fconv-py/model.pt -s en -t fr --save-dir ./ 
`
and this gives the following error:

```
Traceback (most recent call last):
  File "train.py", line 261, in <module>
Process SpawnProcess-1:
    main()
  File "train.py", line 76, in main
Traceback (most recent call last):
  File "/mnt/disks/disk2/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
    extra_state = trainer.load_checkpoint(checkpoint_path)
  File "/mnt/disks/disk2/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_trainer.py", line 131, in load_checkpoint
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_event_loop.py", line 145, in _process_event_loop
    self.error_queue.put((rank, traceback.format_exc()))
KeyboardInterrupt
    for rank in range(self.num_replicas)
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_event_loop.py", line 162, in gen_list
    return [g.gen() for g in gens]
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_event_loop.py", line 162, in <listcomp>
    return [g.gen() for g in gens]
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_event_loop.py", line 158, in gen
    return next(self.generator)
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_event_loop.py", line 37, in result_generator
    yield self.return_pipes[rank].recv()
  File "/mnt/disks/disk2/anaconda3/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/mnt/disks/disk2/anaconda3/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/mnt/disks/disk2/anaconda3/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_event_loop.py", line 91, in _signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably be ignored --

Traceback (most recent call last):
  File "/mnt/disks/disk2/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 476, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /mnt/disks/disk2/pytorch/aten/src/THC/THCTensorCopy.cu:31

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_event_loop.py", line 134, in _process_event_loop
    return_pipe.send(action_fn(rank, device_id, **kwargs))
  File "/mnt/disks/disk2/fairseq-py/fairseq/multiprocessing_trainer.py", line 139, in _async_load_checkpoint
    self.lr_scheduler, cuda_device=device_id)
  File "/mnt/disks/disk2/fairseq-py/fairseq/utils.py", line 83, in load_state
    model.load_state_dict(state['model'])
  File "/mnt/disks/disk2/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 481, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named {}, whose dimensions in the model are {} and whose dimensions in the checkpoint are encoder.embed_tokens.weight.
```

I get this error when I try to restore the provided En-Fr model during train/validation. An error doesn't arise during testing. I am unable to find out the exact source of the problem and how to fix it. Please help me out with this. Thanks!

**Comment by myleott** [comment]
Ah, when training you need to specify the model architecture. Try adding `--arch fconv_wmt_en_fr`. We should improve the error message too.

**Comment by aviralkumar2907** [comment]
Thanks @myleott. It works now.
