### ISSUE TITLE
Error in fairseq/data.py

### ISSUE THREAD

**Issue by playma** [facebookresearch/fairseq-py#55]
Excuse me. I got an error when I pull the new repository

Can anyone help me?

```
Traceback (most recent call last):
  File "pretrain_discriminator.py", line 11, in <module>
    from gan import trainer
  File "/home/playma/Research/fairseq-py/gan/trainer.py", line 1, in <module>
    from fairseq import data, utils
  File "/home/playma/Research/fairseq-py/fairseq/data.py", line 24
    if len(glob.glob(os.path.join(data_dir, f'{split}.*-*.*.bin'))) < 2:
                                                               ^
SyntaxError: invalid syntax
```

**Comment by myleott** [comment]
Ah, it's using the new string format syntax introduced in Python 3.6 [1]. I'll revert that.

[1] https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

**Comment by playma** [comment]
Thanks
