### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zuoxiang95** [facebookresearch/fairseq-py#69]
hello, when i enter command "python setup.py build", i get this error:

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
fatal error: ATen/ATen.h: No such file or directory
 #include <ATen/ATen.h>
compilation terminated.
Traceback (most recent call last):
  File "/root/anaconda3/envs/python_zx/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/root/anaconda3/envs/python_zx/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/root/anaconda3/envs/python_zx/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/root/anaconda3/envs/python_zx/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

I have installed the requirements.

**Comment by myleott** [comment]
ATen is only included in PyTorch versions >= 0.3.0. Did you install PyTorch from source?

**Comment by zuoxiang95** [comment]
Oh, my PyTorch version is 0.2.0. I will try 0.3.0. Thanks for your kind reply.

**Comment by zuoxiang95** [comment]
@myleott Sorry, i only find 0.2.0_3 version in their official website. Can you share a download link for me? Thanks a lot.

**Comment by frankang** [comment]
> Currently fairseq-py requires installing PyTorch from source. Please follow the instructions here: https://github.com/pytorch/pytorch#from-source
See the README file
