### ISSUE TITLE
Run interactive.py error

### ISSUE THREAD

**Issue by playma** [facebookresearch/fairseq-py#72]
I run the interactive.py and get the problem below

```
Traceback (most recent call last):
  File "interactive.py", line 13, in <module>
    from fairseq import options, tokenizer, utils
  File "/home/playma/Research/origin/fairseq-py/fairseq/__init__.py", line 9, in <module>
    from .multiprocessing_pdb import pdb
  File "/home/playma/Research/origin/fairseq-py/fairseq/multiprocessing_pdb.py", line 40, in <module>
    pdb = MultiprocessingPdb()
  File "/home/playma/Research/origin/fairseq-py/fairseq/multiprocessing_pdb.py", line 26, in __init__
    pdb.Pdb.__init__(self, nosigint=True)
TypeError: __init__() got an unexpected keyword argument 'nosigint'
```

**Comment by myleott** [comment]
The `nosigint` keyword argument was added in Python 3.2 [1]. You should probably upgrade to a newer version of Python (we've tested >= 3.5), but you can try removing the `nosigint` keyword from that part of the code and see if it works for you.

[1] https://docs.python.org/3/library/pdb.html#pdb.Pdb

**Comment by playma** [comment]
Maybe the version of Python should be 3.6, because my version is 3.5
And there are some problems with Python 3.6 in Ubuntu 16.04. 

[1] https://stackoverflow.com/questions/41720578/modulenotfounderror-in-tracebacks-with-python3-6-on-linux

**Comment by playma** [comment]
I try again in Python 3.5 and it works. :)
