### ISSUE TITLE
python3 setup.py build error

### ISSUE THREAD

**Issue by huangguanMayday** [facebookresearch/fairseq-py#83]
running build
running build_py
generating /var/folders/_s/f35wwtqs2vxbp9xdcp7hyf8w0000gn/T/tmpugih1w1_/_temporal_convolution_tbc.cpp
running build_ext
building '_temporal_convolution_tbc' extension
creating Users
creating Users/huangguanmayday
creating Users/huangguanmayday/Documents
creating Users/huangguanmayday/Documents/ML_lib
creating Users/huangguanmayday/Documents/ML_lib/fairseq-py-master
creating Users/huangguanmayday/Documents/ML_lib/fairseq-py-master/fairseq
creating Users/huangguanmayday/Documents/ML_lib/fairseq-py-master/fairseq/clib
creating Users/huangguanmayday/Documents/ML_lib/fairseq-py-master/fairseq/clib/temporal_convolution_tbc
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/huangguanmayday/anaconda2/envs/python36/include -arch x86_64 -I/Users/huangguanmayday/anaconda2/envs/python36/include -arch x86_64 -DWITH_CUDA -I/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/Users/huangguanmayday/anaconda2/envs/python36/include/python3.6m -c _temporal_convolution_tbc.cpp -o ./_temporal_convolution_tbc.o -std=c++11
_temporal_convolution_tbc.cpp:434:10: fatal error: 'THC/THC.h' file not found
#include <THC/THC.h>
         ^
1 error generated.
Traceback (most recent call last):
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    'build_py': build_py_hook,
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 51, in run
    conv_tbc.build()
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/Users/huangguanmayday/anaconda2/envs/python36/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by myleott** [comment]
This seems similar to #6. Can you please try the steps listed there and see if they resolve the build issue?
