### ISSUE TITLE
python setup.py build problem.

### ISSUE THREAD

**Issue by lixikun** [facebookresearch/fairseq-py#89]
Hi, I get the following problem when I build,  is it a gcc versoin problem ? My linux is centos 7 and the gcc version is 4.8.5 ?

creating soft/gitproject/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/root/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/root/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/root/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/include/python3.6m -c _temporal_convolution_tbc.cpp -o ./_temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/root/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/root/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/root/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/root/anaconda3/include/python3.6m -c /soft/gitproject/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./soft/gitproject/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/soft/gitproject/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp: In function ‘void TemporalConvolutionTBC_backward(const char*, void*, void*, void*, void*, void*, void*)’:
/soft/gitproject/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:129:9: error: ‘struct at::Tensor’ has no member named ‘assign_’
   dBias.assign_(tmp.sum(0));
         ^
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/root/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/root/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/root/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/root/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/root/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/root/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/root/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/root/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/root/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

**Comment by wolfshow** [comment]
the same problem i met recently.

**Comment by wolfshow** [comment]
Seems because of a recent Ubuntu or pytorch update

**Comment by wolfshow** [comment]
is that because the pytorch update?

**Comment by edunov** [comment]
This is because of a change in pytorch: https://github.com/pytorch/pytorch/pull/4445 
There are also performance issues if fairseq is used with pytorch from master. 

I'd recommend to switch to pytorch branch = v0.3.1 https://github.com/pytorch/pytorch/tree/v0.3.1  it is more stable

**Comment by lixikun** [comment]
@edunov ,thanks you reply!
     I have solve it by modify the code on line 129  in the file  fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp.
     just  comment the following code.
         dBias.assign_(tmp.sum(0));

**Comment by myleott** [comment]
Shouldn't you replace it with copy_ instead? Similar to https://github.com/pytorch/pytorch/pull/4397/files.

**Comment by edunov** [comment]
Agree with @myleott  Commenting it out will make it compile but I'd be surprised if you can still train the model. It will only work for inference.
