### ISSUE TITLE
python setup.py build doesn't work

### ISSUE THREAD

**Issue by aiscientist** [facebookresearch/fairseq-py#93]
I made my own conv s2s and would like to compare with original conv s2s model.
However, I faced those error and not sure how to fix it.
It's mainly about cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
and I looked though all issues, but cannot find the right solution.

running build
running build_py
generating /tmp/tmpv5ojyzzt/_temporal_convolution_tbc.cpp
setting the current directory to '/tmp/tmpv5ojyzzt'
running build_ext
building '_temporal_convolution_tbc' extension
creating home
creating home/ryan
creating home/ryan/git
creating home/ryan/git/fairseq-py
creating home/ryan/git/fairseq-py/fairseq
creating home/ryan/git/fairseq-py/fairseq/clib
creating home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -B /home/ryan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/ryan/anaconda3/include/python3.6m -c _temporal_convolution_tbc.cpp -o ./_temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/ryan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/ryan/anaconda3/include/python3.6m -c /home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp: In function ‘void TemporalConvolutionTBC_backward(const char*, void*, void*, void*, void*, void*, void*)’:
/home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:129:9: error: ‘struct at::Tensor’ has no member named ‘assign_’
   dBias.assign_(tmp.sum(0));
         ^
Traceback (most recent call last):
  File "/home/ryan/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    'build_py': build_py_hook,
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ryan/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 51, in run
    conv_tbc.build()
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 185, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 690, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1515, in recompile
    compiler_verbose, debug)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
ryan@ryanlinux:~/git/fairseq-py$ python setup.py build
running build
running build_py
generating /tmp/tmpxbxoy3dl/_temporal_convolution_tbc.cpp
setting the current directory to '/tmp/tmpxbxoy3dl'
running build_ext
building '_temporal_convolution_tbc' extension
creating home
creating home/ryan
creating home/ryan/git
creating home/ryan/git/fairseq-py
creating home/ryan/git/fairseq-py/fairseq
creating home/ryan/git/fairseq-py/fairseq/clib
creating home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -B /home/ryan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/ryan/anaconda3/include/python3.6m -c _temporal_convolution_tbc.cpp -o ./_temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
gcc -pthread -B /home/ryan/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/ryan/anaconda3/include/python3.6m -c /home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp: In function ‘void TemporalConvolutionTBC_backward(const char*, void*, void*, void*, void*, void*, void*)’:
/home/ryan/git/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:129:9: error: ‘struct at::Tensor’ has no member named ‘assign_’
   dBias.assign_(tmp.sum(0));
         ^
Traceback (most recent call last):
  File "/home/ryan/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
    _build_ext.run(self)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    'build_py': build_py_hook,
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ryan/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/ryan/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 51, in run
    conv_tbc.build()
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 185, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/api.py", line 690, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/recompiler.py", line 1515, in recompile
    compiler_verbose, debug)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/ryan/anaconda3/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1

**Comment by myleott** [comment]
Sorry there's a fix (needed for recent versions of PyTorch) that we didn't merge into the public repo yet. I'll merge it now.

**Comment by myleott** [comment]
Okay, just merged. This is the commit that should fix the build with new versions of PyTorch: 9aca11d2202c03c278fa3fc5c182920070fcd49c.
