### ISSUE TITLE
Does fairseq-py support CUDA 9.1?

### ISSUE THREAD

**Issue by wolfshow** [facebookresearch/fairseq-py#99]
I got the error like this:

Traceback (most recent call last):
  File "train.py", line 294, in <module>
    main()
  File "train.py", line 111, in main
    train(args, epoch, batch_offset, trainer, dataset, max_positions_train)
  File "train.py", line 163, in train
    loss_dict = trainer.train_step(sample)
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_trainer.py", line 207, in train_step
    for rank in range(self.num_replicas)
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_event_loop.py", line 166, in gen_tuple_list
    list = [g.gen() for g in gens]
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_event_loop.py", line 166, in <listcomp>
    list = [g.gen() for g in gens]
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_event_loop.py", line 158, in gen
    return next(self.generator)
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_event_loop.py", line 37, in result_generator
    yield self.return_pipes[rank].recv()
  File "/home/lecu/.conda/envs/py36/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/lecu/.conda/envs/py36/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/lecu/.conda/envs/py36/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_event_loop.py", line 91, in _signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably be ignored --

Traceback (most recent call last):
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_event_loop.py", line 134, in _process_event_loop
    return_pipe.send(action_fn(rank, device_id, **kwargs))
  File "/home/lecu/fairseq-py/fairseq/multiprocessing_trainer.py", line 236, in _async_forward
    self.loss, sample_size, logging_output = self.criterion(self.model, self._sample)
  File "/home/lecu/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lecu/fairseq-py/fairseq/criterions/cross_entropy.py", line 28, in forward
    net_output = model(**sample['net_input'])
  File "/home/lecu/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lecu/fairseq-py/fairseq/models/fairseq_model.py", line 34, in forward
    encoder_out = self.encoder(src_tokens)
  File "/home/lecu/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lecu/fairseq-py/fairseq/models/fconv.py", line 71, in forward
    x = conv(x)
  File "/home/lecu/.conda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lecu/fairseq-py/fairseq/modules/conv_tbc.py", line 45, in forward
    input.contiguous(), self.weight, self.bias, self.padding[0])
  File "/home/lecu/fairseq-py/fairseq/modules/conv_tbc.py", line 76, in forward
    bias)
  File "/home/lecu/.conda/envs/py36/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 198, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
TypeError: initializer for ctype 'void *' must be a cdata pointer, not Variable

**Comment by michaelauli** [comment]
Please provide more background. What is the exact command you ran, what dataset did you use etc.

**Comment by edunov** [comment]
I might be wrong, but this error doesn't look like it has anything to do with CUDA version. 
Have you compiled fairseq-py? (python ./setup.py build; python ./setup.py develop) 
Have you changed anything in the code? 
What command are you running exactly?

**Comment by wolfshow** [comment]
The example

CUDA_VISIBLE_DEVICES=0 python train.py data-bin/iwslt14.tokenized.de-en \
  --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 4000 \
  --arch fconv_iwslt_de_en --save-dir checkpoints/fconv

**Comment by myleott** [comment]
I just pushed a change that replaces the custom ConvTBC module with one built into PyTorch/ATen. Please update fairseq-py and PyTorch and it should work.
